name: Build hello

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
#  schedule:
#    - cron: "0 0 1 * *" # minute (0 - 59) hour (0 - 23) day of the month (1 - 31) month (1 - 12 or JAN-DEC) day of the week (0 - 6 or SUN-SAT)

jobs:
  build-portable:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y --no-install-recommends zip unzip make cmake g++ curl wget

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build hello
        env:
          SAVE_SRC: NO
        run: sh -x build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello_bin
          path: ./*.zip
          if-no-files-found: error

      - name: Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: false
          tag_name: latest
          name: ${{ github.event.client_payload.date }}
          body: "binary"
          files: ./*.zip
