name: Build hello

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
#  schedule:
#    - cron: "0 0 1 * *" # minute (0 - 59) hour (0 - 23) day of the month (1 - 31) month (1 - 12 or JAN-DEC) day of the week (0 - 6 or SUN-SAT)

jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build hello
        run: sh -x build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_bin
          path: ./*.zip
          if-no-files-found: error

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact_bin

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.1
          files: ./*.zip
          body: test version
